######################################################################
# Automatically generated by qmake (2.01a) Paz ?ub 20 20:02:05 2011
######################################################################

TEMPLATE = app
TARGET = BSozluk
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += anaPencere.h higlighter.h
FORMS += anaPencere.ui
SOURCES += anaPencere.cpp highlighter.cpp main.cpp
RESOURCES += ikonlar.qrc
QT += sql
